@startuml
' Basic Configuration
skinparam monochrome true
skinparam shadowing false
autonumber

actor "Professor Jason Smith" as boss
actor "Requester" as requester
actor "Pratik Bhusal" as pratik
actor "Referrer" as referrer

pratik -> boss: Send requester form
activate boss

boss -> requester: Notify form existance

boss -> pratik: Send list of eligible mentors

deactivate boss

...Wait for referral request...

requester -> pratik: Send resume\nand list of companies to request referrals

pratik -> pratik: Check if requester is eligible


group if [Requester eligible]
    requester <-- pratik: Notify that they are eligble\nand that they will send\nreferral request.

    ...Wait for Pratik actually having free time...

    group for each [company referral request]
                pratik -> referrer: Send referral request
        activate referrer

        ...Wait for Referrer to look at request...
        group if [Referrer wants to give referral to Requester]
            group if [Referrer wants to directly talk with Requester]
                requester <-- referrer: Notify final referral steps
            else otherwise
                pratik <-- referrer: Request Pratik to send final referral steps
                deactivate referrer
                requester <-- pratik: Notify final referral steps
            end
        end
    end
end

@enduml
